package com.tt.exam.persistent.mapper;

import com.tt.exam.persistent.entity.ExamJudge;

public interface ExamJudgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_judge
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_judge
     *
     * @mbggenerated
     */
    int insert(ExamJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_judge
     *
     * @mbggenerated
     */
    int insertSelective(ExamJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_judge
     *
     * @mbggenerated
     */
    ExamJudge selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_judge
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_judge
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamJudge record);
}