package com.tt.exam.persistent.mapper;

import com.tt.exam.persistent.entity.ExamOwner;

public interface ExamOwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_owner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_owner
     *
     * @mbggenerated
     */
    int insert(ExamOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_owner
     *
     * @mbggenerated
     */
    int insertSelective(ExamOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_owner
     *
     * @mbggenerated
     */
    ExamOwner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_owner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_owner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamOwner record);
}