package com.tt.exam.persistent.mapper;

import com.tt.exam.persistent.entity.ExamEssay;

public interface ExamEssayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_essay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_essay
     *
     * @mbggenerated
     */
    int insert(ExamEssay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_essay
     *
     * @mbggenerated
     */
    int insertSelective(ExamEssay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_essay
     *
     * @mbggenerated
     */
    ExamEssay selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_essay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamEssay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_essay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ExamEssay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_essay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamEssay record);
}