package com.tt.exam.persistent.mapper;

import com.tt.exam.persistent.entity.Examination;

public interface ExaminationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated
     */
    int insert(Examination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated
     */
    int insertSelective(Examination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated
     */
    Examination selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Examination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Examination record);
}