package com.tt.exam.persistent.mapper;

import com.tt.exam.persistent.entity.SysAdmin;

public interface SysAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated
     */
    int insert(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated
     */
    int insertSelective(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated
     */
    SysAdmin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAdmin record);
}